// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-nfzH7inuosIJqwpCmPs-XmYdhY5LAs',
    appId: '1:186394841501:web:9717e725c79838e5811f74',
    messagingSenderId: '186394841501',
    projectId: 'taskflow-59384',
    authDomain: 'taskflow-59384.firebaseapp.com',
    storageBucket: 'taskflow-59384.firebasestorage.app',
    measurementId: 'G-YYM81MTSGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARF16vh5QvPXaskggQq-F7tloDqH9xA8k',
    appId: '1:186394841501:android:4483448fa6b51739811f74',
    messagingSenderId: '186394841501',
    projectId: 'taskflow-59384',
    storageBucket: 'taskflow-59384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfRGKJm7U5Xk5-qbmTIk1DgLsz-WqgY0',
    appId: '1:186394841501:ios:1a3324fc0a6c8b85811f74',
    messagingSenderId: '186394841501',
    projectId: 'taskflow-59384',
    storageBucket: 'taskflow-59384.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcfRGKJm7U5Xk5-qbmTIk1DgLsz-WqgY0',
    appId: '1:186394841501:ios:1a3324fc0a6c8b85811f74',
    messagingSenderId: '186394841501',
    projectId: 'taskflow-59384',
    storageBucket: 'taskflow-59384.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU-nfzH7inuosIJqwpCmPs-XmYdhY5LAs',
    appId: '1:186394841501:web:9befbd5304da7ed5811f74',
    messagingSenderId: '186394841501',
    projectId: 'taskflow-59384',
    authDomain: 'taskflow-59384.firebaseapp.com',
    storageBucket: 'taskflow-59384.firebasestorage.app',
    measurementId: 'G-ED2Y7BJW9H',
  );
}
